### ISSUE TITLE
New version bump to fix dry-core deprecation warnings?

### ISSUE THREAD

**Issue by ohthatjames** [kirillshevch/query_track#108]
Hi, thank you for fixing the dry gem deprecation warnings in 0f8233d8df25218542b6f53b7e5805fc0e52c567! I was wondering if it was possible for you to release a new version of the gem with those changes, so I can get rid of those warnings in my app?

As a workaround I can point our Gemfile at the latest commit SHA, but it'd be better for us to be using official releases.

**Comment by kirillshevch** [comment]
Hi @ohthatjames!

I've just published [v0.0.12](https://rubygems.org/gems/query_track/versions/0.0.12) version with this commit. Thanks for noticing :+1:

**Comment by ohthatjames** [comment]
Thank you, I really appreciate it!
