### ISSUE TITLE
[FAQ] query_track in production mode

### ISSUE THREAD

**Issue by kirantpatil** [kirillshevch/query_track#25]
Hi,

Do people use query_track in production mode ?

What would be the performance degrade of using it in production mode ?

Thanks.

**Comment by kirillshevch** [comment]
Hi @kirantpatil 

If your project is horizontally scaled, you can install `query_track` for one of node to avoid fully performance degrade.
When we send slack hooks, request is executed in [separate thread](https://github.com/kirillshevch/query_track/blob/30b8cb4a4a9d9b7964c9996d25a28ab864a114e2/lib/query_track/notifications/slack.rb#L21). So there should be no synchronous delays.

**Comment by kirillshevch** [comment]
Subscription to sql execution and time check actually take something in ms. I plan to measure this time and add info to README

**Comment by kirantpatil** [comment]
Great and Thanks a lot.
