### ISSUE TITLE
Use #find instead of #map .include?(false)

### ISSUE THREAD

**Issue by edbond** [kirillshevch/query_track#4]
Return early, use find method

https://github.com/kirillshevch/query_track/blob/5513a30329ab83c95b67c16c4ed14bc923c57373/lib/query_track/filters.rb#L10

**Comment by joxxoxo** [comment]
`any?` would fit better

**Comment by kirillshevch** [comment]
Thanks for paying attention to this. I'll replace with a more optimal solution in the coming days. Or I will be grateful for PRs.

**Comment by kirillshevch** [comment]
fixed
