### ISSUE TITLE
Queries not showing the correct source code location

### ISSUE THREAD

**Issue by glitch003** [kirillshevch/query_track#48]
Hi, 

First of all, thanks for this awesome gem!

I noticed that every query that comes through shows the source code location below, instead of the actual source line of the query:

`/app/vendor/bundle/ruby/2.6.0/gems/query_track-0.0.9/lib/query_track/event_processor.rb:17:in 'call'`

Any idea what might be causing this?  I'm on Rails 5.2.

Thanks!

**Comment by kirillshevch** [comment]
Hi Chris!

Can you share an example of query and actual source location?
