### ISSUE TITLE
Minimal supported version

### ISSUE THREAD

**Issue by DmytroVasin** [kirillshevch/query_track#6]
It would be great to have some note about the minimal supported version.

`ActiveSupport::Notifications.subscribe` is a new feature.

**Comment by kirillshevch** [comment]
It looks like was even in Rails 3.0
https://github.com/rails/rails/blob/3-0-stable/activesupport/lib/active_support/notifications.rb#L58

**Comment by kirillshevch** [comment]
So, I can add the note(and specify `activesupport` 3+ in dependencies).

**Comment by kirillshevch** [comment]
Which version do you exactly use?

**Comment by DmytroVasin** [comment]
@kirillshevch 

I thought it was a new feature due to [recent improvements](https://blog.bigbinary.com/2019/04/24/rails-6-adds-cpu-time-idle-time-and-allocations-to-activesupport-notifications-event.html).

Please close it.
