### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by github0013** [kirillshevch/query_track#67]
I am using the same [Incoming WebHooks][2] ID for different stages. 

I know when you create an Incoming WebHooks ID, it defaults to a channel.   However other library like [stevenosloan/slack-notifier][1], let you choose a channel when to send a notification.

Are we able to select a channel in this block?

```rb
QueryTrack::Settings.configure do |config|
end
```

[1]: https://github.com/stevenosloan/slack-notifier
[2]: https://org-name.slack.com/apps/A0F7XDUAZ-incoming-webhooks?next_id=0

**Comment by kirillshevch** [comment]
Actually not, It based on this library
https://github.com/kirillshevch/slack_hook
